name: app_eclipseworks
description: "Eclipse Work Test Project"
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.6.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_modular: ^6.3.4
  dio: ^5.7.0
  cached_network_image: ^3.4.1
  intl: ^0.20.1
  youtube_player_flutter: ^9.1.1
  photo_view: ^0.15.0
  animations: ^2.0.11
  shared_preferences: ^2.3.4
  material_symbols_icons: ^4.2801.0
  url_launcher: ^6.3.1
  flutter_animate: ^4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mocktail: ^1.0.4
flutter:
  uses-material-design: true